"use client";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const [isOpen, setIsOpen] = useState(false);

  const linkClasses = (path) =>
    `block px-3 py-2 rounded-md ${
      pathname === path ? "bg-blue-500 text-white" : "text-gray-700 hover:bg-gray-200"
    }`;

  return (
    
      
      
    <html lang="en">
      <body className="bg-gray-50">
        {/* Main Content */}
        <main className="max-w-5xl mx-auto p-4">{children}</main>

        {/* Footer */}
      </body>
    </html>
      
  );
}

{/* <html lang="en">
      <body>
        <header>
          <h1>My Website</h1>
          <nav>
            <Link href="/" style={{ fontWeight: pathname === "/" ? "bold" : "normal" }}>
              Home
            </Link>
            <Link
              href="/about"
              style={{ fontWeight: pathname === "/about" ? "bold" : "normal" }}
            >
              About
            </Link>
            <Link
              href="/career"
              style={{ fontWeight: pathname === "/career" ? "bold" : "normal" }}
            >
              Careers
            </Link>

          </nav>
        </header>

        <main>{children}</main>

        <footer>
          <p>© {new Date().getFullYear()} My Website. All rights reserved.</p>
        </footer>
      </body>
    </html> */} 
